core/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('login/', user_login , name='login' ),
    path('logout/', logout_view, name='logout'),
    path('', home, name='home'),
    path('register-patients/', register_patients, name='register-patients'),
    path('edit-patients/<int:id>/', register_patients, name='edit-patients'),
    path('delete_patient/<int:id>', delete_patient, name='delete-patient'),
    path('register-assessment/<int:patient_id>/', submit_assessment, name='register-assessment'),
    path('edit-assessment/<int:id>/<int:patient_id>/', submit_assessment, name='edit-assessment'),
    path('assessment_list/', assessment_list, name='assessment_list'),
    path('delete_assessment/<int:id>', delete_assessment, name='delete-assessment'),



]

hospital/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

core/models.py
from django.db import models
from django.contrib.auth.models import User

class Paciente(models.Model):
    GENERO =(('masculino', 'Masculino'),
             ('feminino', 'Feminino'),
             ('outros', 'Outros'))
    nome = models.CharField(max_length=100)
    data_nascimento = models.DateField()
    genero = models.CharField(choices=GENERO, max_length=20)
    endereco = models.CharField(max_length=255)
    telefone = models.CharField(max_length=20)
    data_criacao = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.nome
    
    def get_assessment(self):
        return AvalicoesSaude.objects.filter(paciente=self).first()

class AvalicoesSaude(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)    
    paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE)
    data_avalicao = models.DateField(auto_now=True)
    sintomas = models.CharField(max_length=255)
    diagnostico_preliminar = models.CharField(max_length=255, blank=True, null=True)
    observacoes = models.CharField(max_length=255, blank=True, null=True)
    
    def __str__(self):
        return self.sintomas

core/forms.py
from django import forms
from .models import *

class RegisterPatientsForm(forms.ModelForm):
    class Meta:
        model = Paciente
        fields = ['nome', 'data_nascimento', 'genero', 'endereco', 'telefone']

        widgets = {
            'nome': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nome'}),
            'data_nascimento': forms.DateInput(attrs={'class': 'form-control', 'placeholder': 'Data de Nascimento'}),
            'genero': forms.Select(attrs={'class': 'form-control', 'placeholder': 'Genero'}),
            'endereco': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ex: Rua, Bairro, numero'}),
            'telefone': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ex: 999999999'}),
        }

class SubmitAssessmentForm(forms.ModelForm):
    class Meta:
        model = AvalicoesSaude
        fields = ['sintomas', 'diagnostico_preliminar', 'observacoes'] 

        widgets = {
            'sintomas': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ex: enchaqueca, nauseas'}),
            'diagnostico_preliminar': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ex: Suspeita de virose'}),
            'observacoes': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ex: a uma semana'}),
        }       

core/views.py
from django.shortcuts import render, redirect , get_object_or_404
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from .forms import *
from .filters import*

def user_login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid() :
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, f"Bem-vindo, {user.username}!")
                return redirect('home')
        else:
            for error in list(form.errors.values()):
                print(error)
    else:
        form = AuthenticationForm()

    return render(request, 'login.html', {"form": form})   

@login_required
def logout_view(request):
    logout(request) 
    return redirect('login') 

@login_required
def home(request):
    paciente_filter = PacienteFilter(request.GET, queryset=Paciente.objects.all())
    count = paciente_filter.qs.count()

    paginator = Paginator(paciente_filter.qs, 5)
    page_num = request.GET.get('page', 1)
    page_obj = paginator.page(page_num)

    return render(request, 'home.html', {'page_obj': page_obj, 'filter': paciente_filter, 'count': count})

@login_required
def register_patients(request, id=None):
    patient = get_object_or_404(Paciente, pk=id) if id else None
    if request.method == "POST":
        form = RegisterPatientsForm(request.POST, instance=patient)
        if form.is_valid():
            form.save()
            return redirect('home')
        else:
            for error in list(form.errors.values()):
                print(error)
    else:
        form = RegisterPatientsForm(instance=patient)

    return render(request, 'register_patients.html', {'form':form, 'patient':patient})


@login_required
def delete_patient(request, id):
    patient = get_object_or_404(Paciente, pk=id)
    if patient:
        patient.delete()

    return redirect('home')    

@login_required
def assessment_list(request):
    assessment_filter = AvaliacaoFilter(request.GET, queryset=AvalicoesSaude.objects.all())
    
    count = assessment_filter.qs.count()


    paginator = Paginator(assessment_filter.qs, 5)
    page_num = request.GET.get('page', 1)
    page_obj = paginator.page(page_num)

    return render(request, 'list_assessment.html', {'page_obj': page_obj, 'filter': assessment_filter , 'count': count})

@login_required
def submit_assessment(request, id=None, patient_id=None):
    assessment = get_object_or_404(AvalicoesSaude, pk=id) if id else None
    patient = get_object_or_404(Paciente, pk=patient_id) if patient_id else None
    if request.method == "POST":
        form = SubmitAssessmentForm(request.POST, instance= assessment)
        if form.is_valid():
            assessment = form.save(commit=False)
            assessment.user = request.user  
            assessment.paciente = patient
            assessment.save()
            return redirect('home')
        else:
            for error in list(form.errors.values()):
                print(error)
    else:
        form = SubmitAssessmentForm(instance= assessment)

    return render(request, 'submit_assessment.html', {'form':form, 'patient': patient})                


@login_required
def delete_assessment(request, id):
    assessment = get_object_or_404(AvalicoesSaude, pk=id)
    if assessment:
        assessment.delete()
        
    return redirect('assessment_list')  

core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'bootstrap-5.3.3/css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,
                  300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">

    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
    <script src="{% static 'bootstrap-5.3.3/js/bootstrap.bundle.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>              
   

    <title>{% block title%} Saúde em Primeiro Lugar {% endblock %}</title>
</head>
<body>
    <!-- ======= Header ======= -->
  <header id="header" class="d-flex align-items-center" >
    <div class="container d-flex align-items-center">

      <h1 class="logo me-auto"><a href="{% url 'home' %}">Saúde em Primeiro Lugar</a></h1>
      <nav id="navbar" class="navbar">
        <ul>
            <li><a class="nav-link scrollto " href="{% url 'home' %}">Lista de Pacientes</a></li>
            <li><a class="nav-link scrollto  " href="{% url 'register-patients' %}">Cadastrar Paciente</a></li>
            <li><a class="nav-link scrollto  " href="{% url 'assessment_list' %}" >Histórico de Avaliações</a></li>  
            <li><a class="getstarted scrollto" href="{% url 'logout' %}" >Logout</a></li>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav>
    </div>
  </header><!-- End Header -->
  
    {% block content %}
    {% endblock %}

  <footer class="my-5 pt-5 text-body-secondary text-center text-small">
    <p class="mb-1">© 2024 Victor Vasconcelos</p>
    <ul class="list-inline">
      <li class="list-inline-item"><a href="https://www.linkedin.com/in/victor-vasconcelos-barbosa/">Linkedin</a></li>
      <li class="list-inline-item"><a href="https://github.com/VasconcelosVictor">Git Hub</a></li>
      
    </ul>
  </footer>

</body>
</html>

core/templates/base_clean.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'bootstrap-5.3.3/css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">

    <title>{% block title%} Saúde em Primeiro Lugar {% endblock %}</title>
</head>
<body>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    
    <footer class="my-5 pt-5 text-body-secondary text-center text-small">
        <p class="mb-1">© 2024 Victor Vasconcelos</p>
        <ul class="list-inline">
          <li class="list-inline-item"><a href="https://www.linkedin.com/in/victor-vasconcelos-barbosa/">Linkedin</a></li>
          <li class="list-inline-item"><a href="https://github.com/VasconcelosVictor">Git Hub</a></li>
          
        </ul>
      </footer>
</body>
<script src="{% static 'bootstrap-5.3.3/js/bootstrap.bundle.min.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
{% block extra_js %}{% endblock %}
</html>

core/templates/home.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="container">
  <div class="text-center">
    <img src="{% static 'img/atendimento_banner.jpg' %}" class="img-fluid" width="400px" 
    style="margin-bottom: 30px; border-radius: 20px; margin-top: 50px;" alt="banner-principal">
  </div>
  <div class="text-center"><h2>Lista de Pacientes</h2></div>
  <hr>
  
  <div>
    <div class="d-flex justify-content-between mb-3">
      <button type="button" class="btn default-color" data-bs-toggle="modal" data-bs-target="#filterModal">
        Filtros <i class='bx bx-filter-alt'></i>
      </button>
    </div>
  </div>
  
  <br>
  
  {% if page_obj %}
  <div class="card">
    <div class="table-responsive"> 
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Nome</th>
            <th scope="col">Data de Nascimento</th>
            <th scope="col">Gênero</th>
            <th scope="col">Endereço</th>
            <th scope="col">Telefone</th>
            <th scope="col">Data de Criação</th>
          </tr>
        </thead>
        <tbody class="table-group-divider">
          {% for patient in page_obj %}
          <tr style="cursor:pointer;">
            <th scope="row">{{ forloop.counter }}</th>
            <td><a href="{% url 'edit-patients' patient.id %}">{{ patient.nome | upper }}</a></td>
            <td> <a href="{% url 'edit-patients' patient.id %}">{{ patient.data_nascimento | date:"d/m/Y" }}</a> </td>
            <td> <a href="{% url 'edit-patients' patient.id %}">{{ patient.genero | upper }}</a></td>
            <td> <a href="{% url 'edit-patients' patient.id %}">{{ patient.endereco | upper }}</a></td>
            <td><a href="{% url 'edit-patients' patient.id %}">{{ patient.telefone | upper }}</a> </td>
            <td> <a href="{% url 'edit-patients' patient.id %}">{{ patient.data_criacao | date:"d/m/Y H:i" }}</a> </td>
            {% if patient.get_avaliacao %}
              <td>
                <a href="{% url 'edit-assessment' patient.get_assessment.id patient.id %}" 
                class="btn default-color"> Avalicao
                </a>
              </td>
            {% else %}
              <td ><a href="{% url 'register-assessment'  patient.id %}" class="btn default-color"> Avalicao</a></td>
            {% endif %}  
              <td><button type="button" data-patient-id="{{ patient.id }}"  class="btn btn-danger-color delete-button">Excluir</button></td>
          </tr> 
          {% empty %}
          <tr>
            <th scope="row">1</th>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
          </tr>    
          {% endfor %}
        </tbody>
      </table>
    </div> 
  </div>
  
  <div class="pagination">
    {% include "paginate.html" %}
  </div>
  
  <div>
    <p>Itens {{ count }} </p>
    <hr>
  </div>
  {% endif %}
</div>

<!-- Modal -->
<div class="modal fade" id="filterModal" tabindex="-1" aria-labelledby="filterModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="filterModalLabel">Filtros</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form method="get" action="">
          <div class="form-group">
            <label for="id_nome">Nome:</label>
            {{ filter.form.nome }}
          </div>
          <div class="form-group">
            <label for="id_nome">Gênero:</label>
            {{ filter.form.genero }}
          </div>

          <div class="form-group">
            <label for="id_data_nascimento">Data da Avaliação Inicial:</label>
            <input type="text" name="data_nascimento_after" class="form-control"  id="id_data_nascimento_0">
            
        </div>
        <div class="form-group">
          <label for="id_data_nascimento">Data da Avaliação Final:</label>
          
          <input type="text" name="data_nascimento_before" class="form-control" id="id_data_nascimento_1">
        </div>
          
          <br>
          
          <div>
            <button type="submit" class="btn btn-success">Filtrar</button>
          </div>
          
        </form>
        
      </div>
      
    </div>
  </div>
</div>

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script src="https://cdn.jsdelivr.net/npm/flatpickr/dist/l10n/pt.js"></script>

<script >
  
$(document).ready(function(){
  flatpickr("#id_data_nascimento_0", {
        dateFormat: "d/m/Y",  
        altInput: true,       
        altFormat: "d/m/Y",   
        allowInput: true      
    });

    flatpickr("#id_data_nascimento_1", {
        dateFormat: "d/m/Y",
        altInput: true,
        altFormat: "d/m/Y",
        allowInput: true
    });
})



document.addEventListener("DOMContentLoaded", function() {
    const deleteButtons = document.querySelectorAll('.delete-button');

    deleteButtons.forEach(button => {
        button.addEventListener('click', function() {
            const patientId = this.getAttribute('data-patient-id');

            Swal.fire({
                title: 'Tem certeza que deseja excluir esse paciente?',
                text: 'Após confirmar essa ação ela não poderá ser revertida.',
                icon: 'warning',
                showCancelButton: true,
                confirmButtonText: 'Confirmar',
                confirmButtonColor: '#5cb874',
                cancelButtonText: 'Cancelar',
                cancelButtonColor: '#d33'
            }).then((result) => {
                if (result.isConfirmed) {
                    window.location.href = `{% url 'delete-patient' 0 %}`.replace('0', patientId);
                }
            });
        });
    });
});


</script>

{% endblock %}

core/templates/list_assessment.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="container">
  <div class="text-center">
    <img src="{% static 'img/historico.jpg' %}" class="img-fluid" width="400px" 
    style="margin-bottom: 30px; border-radius: 20px; margin-top: 50px;" alt="banner-principal">
  </div>
  <div class="text-center"><h2>Histórico de Avaliações</h2></div>
  <hr>
  
  <div>
    <div class="d-flex justify-content-between mb-3">
      <button type="button" class="btn default-color" data-bs-toggle="modal" data-bs-target="#filterModal">
        Filtros <i class='bx bx-filter-alt'></i>
      </button>
    </div>
  </div>

  <br>
  
  {% if page_obj %}
  <div class="card">
    <div class="table-responsive"> 
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Usuário</th>
            <th scope="col">Paciente</th>
            <th scope="col">Data da Avalição</th>
            <th scope="col">Sintomas</th>
            <th scope="col">Diagnostico</th>
            <th scope="col">Observações</th>
          </tr>
        </thead>
        <tbody class="table-group-divider">
          {% for assessment in page_obj %}
          <tr style="cursor:pointer;">
            <th scope="row">{{ forloop.counter }}</th>
            <td><a href="{% url 'edit-assessment' assessment.id assessment.paciente.id %}">{{ assessment.user | upper }}</a></td>
            <td><a href="{% url 'edit-assessment' assessment.id assessment.paciente.id %}">{{ assessment.paciente | upper }}</a></td>
            <td><a href="{% url 'edit-assessment' assessment.id assessment.paciente.id %}">{{ assessment.data_avalicao | date:"d/m/Y"  }}</a></td>
            <td><a href="{% url 'edit-assessment' assessment.id assessment.paciente.id %}">{{ assessment.sintomas | upper }}</a></td>
            <td><a href="{% url 'edit-assessment' assessment.id assessment.paciente.id %}">{{ assessment.diagnostico_preliminar | upper }}</a></td>
            <td><a href="{% url 'edit-assessment' assessment.id assessment.paciente.id %}">{{ assessment.observacoes | upper }}</a></td>
            <td><button type="button" data-assessment-id="{{ assessment.id }}"  class="btn btn-danger-color delete-button">Excluir</button></td>
          </tr> 
          {% empty %}
          <tr>
            <th scope="row">1</th>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
            <td>-</td>
          </tr>    
          {% endfor %}
        </tbody>
      </table>
    </div> 
  </div>
  
  <div class="pagination">
    {% include "paginate.html" %}
  </div>
  
  <div>
    <p id="t">Itens {{ count }} </p>
    <hr>
  </div>
  {% endif %}
</div>

<!-- Modal -->
<div class="modal fade" id="filterModal" tabindex="-1" aria-labelledby="filterModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="filterModalLabel">Filtros</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form method="get" action="">
          <div class="form-group">
            <label for="id_paciente">Paciente:</label>
            {{ filter.form.paciente }}
          </div>
          <div class="form-group">
            <label for="id_sintomas">Sintomas:</label>
            {{ filter.form.sintomas }}
          </div>

        <div class="form-group">
            <label for="id_data_avalicao">Data da Avaliação Inicial:</label>
            <input type="text" name="data_avalicao_after" class="form-control"  id="id_data_avalicao_0">
            
        </div>
        <div class="form-group">
          <label for="id_data_avalicao">Data da Avaliação Final:</label>
          
          <input type="text" name="data_avalicao_before" class="form-control" id="id_data_avalicao_1">
        </div>
          
          <br>
          <div>
            <button type="submit" class="btn btn-success">Filtrar</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script src="https://cdn.jsdelivr.net/npm/flatpickr/dist/l10n/pt.js"></script>
<script>

  
    flatpickr("#id_data_avalicao_inicial", {
        dateFormat: "d/m/Y",  // Formato de data DD/MM/AAAA
        altInput: true,       // Mostra um campo formatado
        altFormat: "d/m/Y",   // Formato exibido ao usuário
        allowInput: true ,
        locale: "pt"       // Permite inserir manualmente a data
    });

    flatpickr("#id_data_avalicao_final", {
        dateFormat: "d/m/Y",
        altInput: true,
        altFormat: "d/m/Y",
        allowInput: true,
        locale: "pt"  
    });

</script>

<script>
  document.addEventListener("DOMContentLoaded", function() {
    const deleteButtons = document.querySelectorAll('.delete-button');

    deleteButtons.forEach(button => {
        button.addEventListener('click', function() {
            const patientId = this.getAttribute('data-assessment-id');

            Swal.fire({
                title: 'Tem certeza que deseja excluir essa avaliação?',
                text: 'Após confirmar essa ação ela não poderá ser revertida.',
                icon: 'warning',
                showCancelButton: true,
                confirmButtonText: 'Confirmar',
                confirmButtonColor: '#5cb874',
                cancelButtonText: 'Cancelar',
                cancelButtonColor: '#d33'
            }).then((result) => {
                if (result.isConfirmed) {
                    window.location.href = `{% url 'delete-assessment' 0 %}`.replace('0', patientId);
                }
            });
        });
    });
});

</script>

{% endblock %}

core/templates/login.html
{% extends 'base_clean.html' %}
{% load static %}
{%block title %} Login {% endblock %}
{% block content %}
{% if messages %}
<ul>
  {% for message in messages %}
    <li>{{ message }}</li>
  {% endfor %}
</ul>
{% endif %}


<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card mt-5">
                <div class="card-header text-center">
                    
                    <img src="{% static 'img/logo.png'%}" alt="logo">
                    <br>
                    <br>
                    <h4>Login</h4>
                </div>
                <div class="container-fluid">
                    <form method="post" action="">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="id_username">Username</label>
                            <input class="form-control" id="id_username" name="username" type="text" placeholder="Username" aria-label="default input example">
                            <div class="smal-erros">
                              {{ form.username.errors }}
                            </div>
                            
                        </div>
                        <div class="form-group">
                            <label for="inputPassword5" class="form-label">Senha</label>
                            <input type="password" name="password" id="id_password" class="form-control" aria-describedby="passwordHelpBlock">
                            <div id="passwordHelpBlock" class="form-text">
                              
                            </div>
                            <div class="smal-erros">
                              {{ form.password.errors }}
                            </div> 
                        </div>
                      </div>
                        <!-- <button id="btn-login" type="submit" class="">Login</button> -->
                        <button type="submit" class="btn  default-color">Login</button>
                    
                    </form>

                </div>
            </div>
        </div>            
        
    </div>
  </div>

{% endblock %}

core/templates/register_patients.html
{% extends 'base.html' %}

{% block content %}
<div style="margin-top: 70px;" class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card mt-5">
                <div class="card-header text-center">
                {% if patient %}
                    <h4>Editar Paciente</h4>
                {% else %}
                    <h4>Cadastrar Paciente</h4>
                {% endif %}
                    
                </div>
                <div class="card-body">
                
                  <form method="post" action="">
                      {% csrf_token %}
                      {{ form.non_field_errors }}
                      <div class="form-group">
                          <label for="id_nome">Nome:</label>
                          {{ form.nome }}
                          <div class="smal-erros">
                              {{ form.nome.errors }}
                          </div>
                      </div>
                      <div class="form-group">
                          <label for="id_data_nascimento">Data de Nascimento:</label>
                          {{ form.data_nascimento }}
                          <div class="smal-erros">
                              {{ form.data_nascimento.errors }}
                          </div>
                      </div>
                      <div class="form-group">
                          <label for="id_genero">Genero:</label>
                          {{ form.genero }}
                          <div class="smal-erros">
                              {{ form.genero.errors }}
                          </div>
                      </div>
                      <div class="form-group">
                          <label for="id_endereco">Endereço:</label>
                          {{ form.endereco }}
                          <div class="smal-erros">
                              {{ form.endereco.errors }}
                          </div>
                      </div>
                      <div class="form-group ">
                          <label for="id_telefone">Telefone:</label>
                          {{ form.telefone }}
                          <div class="smal-erros">
                              {{ form.telefone.errors }}
                          </div>
                      </div>
                      <div class="form-group  text-center">
                        <button type="submit" class="btn  default-color w-100 mt-3">Salvar</button>
                      </div>
                      
                  </form>
              </div>
            </div>
        </div>
    </div>
  </div>
{% endblock %}

core/templates/submit_assessment.html
{% extends 'base.html' %}

{% block content %}
<div style="margin-top: 70px;" class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card mt-5">
                <div class="card-header text-center">
                {% if patient %}
                    <h4>Editar Avalicao </h4>
                {% else %}
                    <h4>Cadastrar Avalicao</h4>
                {% endif %}
                    <p>Paciente : {{patient}}</p>
                </div>
                <div class="card-body">
                  <form method="post" action="">
                      {% csrf_token %}
                      {{ form.non_field_errors }}
                      <div class="form-group">
                          <label for="id_sintomas">Sintomas:</label>
                          {{ form.sintomas }}
                          <div class="smal-erros">
                              {{ form.sintomas.errors }}
                          </div>
                      </div>
                      <div class="form-group">
                          <label for="id_diagnostico_preliminar">Diagnostivo Preliminar :</label>
                          {{ form.diagnostico_preliminar }}
                          <div class="smal-erros">
                              {{ form.diagnostico_preliminar.errors }}
                          </div>
                      </div>
                      <div class="form-group ">
                          <label for="id_observacoes">Observações:</label>
                          {{ form.observacoes }}
                          <div class="smal-erros">
                              {{ form.observacoes.errors }}
                          </div>
                      </div>
                      <div class="form-group  text-center">
                        <button type="submit" class="btn  default-color w-100 mt-3">Salvar</button>
                      </div>
                  </form>
              </div>
            </div>
        </div>
    </div>
  </div>
{% endblock %}